In [ ]:
# create model class
import torch
import torch.nn as nn


class Model(nn.Module): # inheriting from nn.Module class
    def __init__(self, num_features):
        super().__init__()
        
        # self.linear = nn.Linear(num_features, 1)
        # self.sigmoid = nn.Sigmoid()
        
        # self.linear1 = nn.Linear(num_features, 3)
        # self.relu = nn.ReLU()
        # self.linear2 = nn.Linear(3,1)
        # self.sigmoid = nn.Sigmoid()
        
        self.network = nn.Sequential( # sequential container
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        
    def forward(self, features):
        # out = self.linear1(features)
        # out = self.relu(out)
        # out = self.linear2(out)
        # out = self.sigmoid(out)
        
        out = self.network(features)
    
        return out
    
    

In [25]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features) # we can do that but it's not recommended
model(features) # forward method is triggered itself *IMP - Magic Method

tensor([[0.5007],
        [0.5007],
        [0.5007],
        [0.5007],
        [0.5007],
        [0.5007],
        [0.5007],
        [0.5007],
        [0.5007],
        [0.5007]], grad_fn=<SigmoidBackward0>)

In [26]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[-0.0928, -0.3230, -0.1318, -0.3260, -0.4194],
        [ 0.0189, -0.4012, -0.0417,  0.0198, -0.2552],
        [-0.2132,  0.3589,  0.0235,  0.0842, -0.2519]], requires_grad=True)

In [27]:
model.linear1.bias

Parameter containing:
tensor([ 0.0697, -0.1954, -0.3011], requires_grad=True)

In [ ]:
# !pip install torchinfo

In [28]:
from torchinfo import summary

summary(model, input_size=(10,5))



Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00