In [1]:
import torch
import torch.nn as nn

In [9]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # self.linear = nn.Linear(num_features, 1) # input features and output features
        # self.sigmoid = nn.Sigmoid()
        
        #---------------- Improved Code
        self.linear1 = nn.Linear(num_features, 3) # input features and output features
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        # out = self.linear(features)
        # out = self.sigmoid(out)
        
        #---------------- Improved Code
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [10]:
# dataset creation
features = torch.rand(10,5)

# model creation
model = Model(features.shape[1])

# call model for forward pass
model(features) # same as model.forward(features), in a standard way. This is a magic method

tensor([[0.5153],
        [0.5135],
        [0.4906],
        [0.5016],
        [0.5069],
        [0.5107],
        [0.4868],
        [0.5223],
        [0.5025],
        [0.4637]], grad_fn=<SigmoidBackward0>)

In [11]:
# show model's weights
print(model.linear1.bias)
model.linear1.weight

Parameter containing:
tensor([ 0.3390, -0.4129,  0.1890], requires_grad=True)


Parameter containing:
tensor([[-0.2532,  0.0055,  0.3515, -0.3284,  0.1421],
        [-0.3266,  0.3686, -0.0878, -0.0355,  0.3005],
        [ 0.0715,  0.4234,  0.3014,  0.2747,  0.3711]], requires_grad=True)

In [7]:
from torchinfo import summary

In [12]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [17]:
# Sequential Container

class Model2(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3), 
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        
    def forward(self, features):
        out = self.network(features)
        return out

In [18]:
# dataset creation
features = torch.rand(10,5)

# model creation
model = Model2(features.shape[1])

# call model for forward pass
model(features) # same as model.forward(features), in a standard way. This is a magic method

tensor([[0.5417],
        [0.5648],
        [0.5595],
        [0.5778],
        [0.5426],
        [0.5878],
        [0.5752],
        [0.5837],
        [0.5934],
        [0.5723]], grad_fn=<SigmoidBackward0>)