<a href="https://colab.research.google.com/github/SakshiKhatiwada/Python/blob/main/PyTorch/tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print("GPU: ", torch.cuda.get_device_name())
else:
  print("GPU is not available")

GPU is available
GPU:  Tesla T4


## Creating a Tensor

In [25]:
# using empty
a = torch.empty(3,5) # memory allocation, doesn't initialize
a

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [6]:
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones

torch.ones(1,2)

tensor([[1., 1.]])

In [9]:
# using rand

torch.rand(2,3) # initialized between 0 and 1

tensor([[0.1434, 0.0510, 0.4080],
        [0.8281, 0.5472, 0.4017]])

In [12]:
# use of manual_seed
torch.manual_seed(100)
print(torch.rand(2,3))
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
# custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
# other ways

# arange
print("using arange -> ", torch.arange(0,10,2)) # start, end, step

# linspace
print("using linspace: ", torch.linspace(0,10,10))

# eye
print("using eye: ", torch.eye(5))

# full
print("using full: \n", torch.full((3,3), 5))


using arange ->  tensor([0, 2, 4, 6, 8])
using linspace:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full: 
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [20]:
a = torch.tensor([[1,2,3], [7,8,9]], dtype=torch.float)
a.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(a)

tensor([[3616445622929465956, 6066966817835855157, 3976742458216822832],
        [6501007867614736942, 7309453675965983778, 8315168162784306286]])

In [22]:
torch.zeros_like(a)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(a)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [37]:
# torch.rand_like(a.to(torch.float32))
torch.rand_like(a, dtype=torch.float32)
# error because a has integer and rand gives float data

tensor([[0.9535, 0.7064, 0.1629, 0.8902, 0.5163],
        [0.0359, 0.6476, 0.3430, 0.3182, 0.5261],
        [0.0447, 0.5123, 0.9051, 0.5989, 0.4450]])

## Tensor Data Types

In [28]:
# find data type
a.dtype

torch.float32

In [32]:
# assign datatype while creating
torch.tensor([1,2,3], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [34]:
# using to()
a.to(torch.float32)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

## Mathematical Operations

In [46]:
a = torch.tensor([1,2,3], dtype=torch.int32)
print(a + 2)
print(a - 3)
print(a * 4)
print(a / 2 )
print(a * 5)
print(a//2)
print(a % 2)
print('multiply: ',a * 5)
print(a**2)

tensor([3, 4, 5], dtype=torch.int32)
tensor([-2, -1,  0], dtype=torch.int32)
tensor([ 4,  8, 12], dtype=torch.int32)
tensor([0.5000, 1.0000, 1.5000])
tensor([ 5, 10, 15], dtype=torch.int32)
tensor([0, 1, 1], dtype=torch.int32)
tensor([1, 0, 1], dtype=torch.int32)
multiply:  tensor([ 5, 10, 15], dtype=torch.int32)
tensor([1, 4, 9], dtype=torch.int32)


In [49]:
# element-wise operation
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a,"\n", b)
a + b # element-wise operations

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]]) 
 tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])


tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [52]:
# abs
torch.abs(torch.tensor([1,-2,3]))

tensor([1, 2, 3])

In [53]:
torch.neg(torch.tensor([1,-2,3]))

tensor([-1,  2, -3])

In [54]:
d = torch.tensor([1,2.3, 4.1, 5.5])
torch.round(d)

tensor([1., 2., 4., 6.])

In [55]:
print("ceiling: ", torch.ceil(d))
print("floor: ", torch.floor(d))

ceiling:  tensor([1., 3., 5., 6.])
floor:  tensor([1., 2., 4., 5.])


In [57]:
# clamp
torch.clamp(d, min=2, max=4)

tensor([2.0000, 2.3000, 4.0000, 4.0000])

## Reduction Operation

In [62]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[4, 1, 1],
        [2, 4, 7]])

In [59]:
# sum
torch.sum(e)

tensor(20)

In [63]:
# sum along columns and rows
torch.sum(e, dim=0) # col wise
torch.sum(e, dim=1) # row wise

tensor([ 6, 13])

In [68]:
# mean
# torch.mean(e) # only works with float, not long
f = e.to(dtype=torch.float32)
torch.mean(f)

tensor(3.1667)

In [69]:
# mean along rows and columns
torch.mean(f, dim=0)

tensor([3.0000, 2.5000, 4.0000])

In [71]:
# median
torch.median(f)

tensor(2.)

In [73]:
# max and min
print(torch.max(f))
torch.min(f)

tensor(7.)


tensor(1.)

In [74]:
torch.prod(e)

tensor(224)

In [75]:
torch.std(f)

tensor(2.3166)

In [77]:
# variance
torch.var(f)

tensor(5.3667)