<a href="https://colab.research.google.com/github/SakshiKhatiwada/Python/blob/main/PyTorch/tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print("GPU: ", torch.cuda.get_device_name())
else:
  print("GPU is not available")

GPU is available
GPU:  Tesla T4


## Creating a Tensor

In [ ]:
# using empty
a = torch.empty(3,5) # memory allocation, doesn't initialize
a

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones

torch.ones(1,2)

tensor([[1., 1.]])

In [ ]:
# using rand

torch.rand(2,3) # initialized between 0 and 1

tensor([[0.1434, 0.0510, 0.4080],
        [0.8281, 0.5472, 0.4017]])

In [ ]:
# use of manual_seed
torch.manual_seed(100)
print(torch.rand(2,3))
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange -> ", torch.arange(0,10,2)) # start, end, step

# linspace
print("using linspace: ", torch.linspace(0,10,10))

# eye
print("using eye: ", torch.eye(5))

# full
print("using full: \n", torch.full((3,3), 5))


using arange ->  tensor([0, 2, 4, 6, 8])
using linspace:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full: 
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
a = torch.tensor([[1,2,3], [7,8,9]], dtype=torch.float)
a.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(a)

tensor([[3616445622929465956, 6066966817835855157, 3976742458216822832],
        [6501007867614736942, 7309453675965983778, 8315168162784306286]])

In [ ]:
torch.zeros_like(a)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(a)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# torch.rand_like(a.to(torch.float32))
torch.rand_like(a, dtype=torch.float32)
# error because a has integer and rand gives float data

tensor([[0.9535, 0.7064, 0.1629, 0.8902, 0.5163],
        [0.0359, 0.6476, 0.3430, 0.3182, 0.5261],
        [0.0447, 0.5123, 0.9051, 0.5989, 0.4450]])

## Tensor Data Types

In [ ]:
# find data type
a.dtype

torch.float32

In [ ]:
# assign datatype while creating
torch.tensor([1,2,3], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
a.to(torch.float32)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

## Mathematical Operations

In [ ]:
a = torch.tensor([1,2,3], dtype=torch.int32)
print(a + 2)
print(a - 3)
print(a * 4)
print(a / 2 )
print(a * 5)
print(a//2)
print(a % 2)
print('multiply: ',a * 5)
print(a**2)

tensor([3, 4, 5], dtype=torch.int32)
tensor([-2, -1,  0], dtype=torch.int32)
tensor([ 4,  8, 12], dtype=torch.int32)
tensor([0.5000, 1.0000, 1.5000])
tensor([ 5, 10, 15], dtype=torch.int32)
tensor([0, 1, 1], dtype=torch.int32)
tensor([1, 0, 1], dtype=torch.int32)
multiply:  tensor([ 5, 10, 15], dtype=torch.int32)
tensor([1, 4, 9], dtype=torch.int32)


In [ ]:
# element-wise operation
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a,"\n", b)
a + b # element-wise operations

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]]) 
 tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])


tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [ ]:
# abs
torch.abs(torch.tensor([1,-2,3]))

tensor([1, 2, 3])

In [ ]:
torch.neg(torch.tensor([1,-2,3]))

tensor([-1,  2, -3])

In [ ]:
d = torch.tensor([1,2.3, 4.1, 5.5])
torch.round(d)

tensor([1., 2., 4., 6.])

In [ ]:
print("ceiling: ", torch.ceil(d))
print("floor: ", torch.floor(d))

ceiling:  tensor([1., 3., 5., 6.])
floor:  tensor([1., 2., 4., 5.])


In [ ]:
# clamp
torch.clamp(d, min=2, max=4)

tensor([2.0000, 2.3000, 4.0000, 4.0000])

## Reduction Operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[4, 1, 1],
        [2, 4, 7]])

In [ ]:
# sum
torch.sum(e)

tensor(20)

In [ ]:
# sum along columns and rows
torch.sum(e, dim=0) # col wise
torch.sum(e, dim=1) # row wise

tensor([ 6, 13])

In [ ]:
# mean
# torch.mean(e) # only works with float, not long
f = e.to(dtype=torch.float32)
torch.mean(f)

tensor(3.1667)

In [ ]:
# mean along rows and columns
torch.mean(f, dim=0)

tensor([3.0000, 2.5000, 4.0000])

In [ ]:
# median
torch.median(f)

tensor(2.)

In [ ]:
# max and min
print(torch.max(f))
torch.min(f)

tensor(7.)


tensor(1.)

In [ ]:
torch.prod(e)

tensor(224)

In [ ]:
torch.std(f)

tensor(2.3166)

In [ ]:
# variance
torch.var(f)

tensor(5.3667)

# Matrix Operations

In [ ]:
f = torch.tensor([1,2,3])
g = torch.tensor([4,3,2])

torch.matmul(f,g)

tensor(16)

In [ ]:
a = torch.randint(size=(2,3), low=3, high=9)
b = torch.randint(size=(3,4), low=4, high=8)

print('a', a)
print('b', b)
torch.matmul(a,b)

a tensor([[4, 5, 6],
        [7, 8, 5]])
b tensor([[7, 4, 5, 4],
        [6, 7, 5, 4],
        [6, 6, 7, 5]])


tensor([[ 94,  87,  87,  66],
        [127, 114, 110,  85]])

In [ ]:
# dot products

vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1, vector2)

tensor(11)

In [ ]:
print(a)
torch.transpose(a, 0, 1) # matrix, dim0, dim1 to swap

tensor([[4, 5, 6],
        [7, 8, 5]])


tensor([[4, 7],
        [5, 8],
        [6, 5]])

In [ ]:
torch.transpose(vector1, 0, -1) # does nothing as it only has one dimension

tensor([1, 2])

In [ ]:
x = torch.tensor([[8.0, 2., 2.], [4.,8.,8.],[5., 0., 4.]], dtype=torch.float32)
print(x)
torch.det(x)

tensor([[8., 2., 2.],
        [4., 8., 8.],
        [5., 0., 4.]])


tensor(224.)

In [ ]:
# inverse
torch.inverse(x)

tensor([[ 0.1429, -0.0357,  0.0000],
        [ 0.1071,  0.0982, -0.2500],
        [-0.1786,  0.0446,  0.2500]])

## Comparison Operations

In [ ]:
print(f)
print(g)
f>g

tensor([1, 2, 3])
tensor([4, 3, 2])


tensor([False, False,  True])

In [ ]:
print(f<g)
print(f==g)
print(f!=g)
print(f>=g)
print(f<=g)

tensor([ True,  True, False])
tensor([False, False, False])
tensor([True, True, True])
tensor([False, False,  True])
tensor([ True,  True, False])


## Special Functions

In [ ]:
torch.manual_seed(4)
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 4., 1.],
        [3., 9., 6.]])

In [ ]:
torch.log(k)

tensor([[  -inf, 1.3863, 0.0000],
        [1.0986, 2.1972, 1.7918]])

In [ ]:
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 2.7183e+00],
        [2.0086e+01, 8.1031e+03, 4.0343e+02]])

In [ ]:
torch.sqrt(k)

tensor([[0.0000, 2.0000, 1.0000],
        [1.7321, 3.0000, 2.4495]])

In [ ]:
torch.sigmoid(k)

tensor([[0.5000, 0.9820, 0.7311],
        [0.9526, 0.9999, 0.9975]])

In [ ]:
torch.softmax(k, dim=0)

tensor([[0.0474, 0.0067, 0.0067],
        [0.9526, 0.9933, 0.9933]])

In [ ]:
torch.relu(k)

tensor([[0., 4., 1.],
        [3., 9., 6.]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [ ]:
print(m,'\n',n)

tensor([[0.9929, 0.9131, 0.6186],
        [0.9744, 0.3189, 0.2148]]) 
 tensor([[0.9263, 0.4735, 0.5949],
        [0.7956, 0.7635, 0.2137]])


In [ ]:
m + n # occupies separate memory

tensor([[1.9192, 1.3866, 1.2135],
        [1.7700, 1.0824, 0.4285]])

In [ ]:
m.add_(n) # replaces m

tensor([[1.9192, 1.3866, 1.2135],
        [1.7700, 1.0824, 0.4285]])

In [ ]:
m

tensor([[1.9192, 1.3866, 1.2135],
        [1.7700, 1.0824, 0.4285]])

In [ ]:
m.relu_() # permanent change to m

tensor([[1.9192, 1.3866, 1.2135],
        [1.7700, 1.0824, 0.4285]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.6043, 0.3836, 0.2663],
        [0.8823, 0.2978, 0.7466]])

In [ ]:
b = a

In [ ]:
# b = b + 1 # not a great example here, it just created a new one
print(a)
print(b)

tensor([[0.6043, 0.3836, 0.2663],
        [0.8823, 0.2978, 0.7466]])
tensor([[0.6043, 0.3836, 0.2663],
        [0.8823, 0.2978, 0.7466]])


In [ ]:
a[0][0] = 0
print(a)
print(b)

tensor([[0.0000, 0.3836, 0.2663],
        [0.8823, 0.2978, 0.7466]])
tensor([[0.0000, 0.3836, 0.2663],
        [0.8823, 0.2978, 0.7466]])


In [ ]:
print(id(a))
print(id(b))

138776054363184
138776054363184


In [ ]:
# copying tensor
b = a.clone()
print(id(a))
print(id(b))

138776054363184
138771401942080


## Tensor Operations on GPU

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.cuda.get_device_name()

'Tesla T4'

In [ ]:
device = torch.device('cuda')
device

device(type='cuda')

In [ ]:
# creating new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.0360, 0.5415, 0.1626],
        [0.8106, 0.4422, 0.6999]], device='cuda:0')

In [ ]:
# moving existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.4830, 0.4738, 0.8391],
        [0.1054, 0.9248, 0.1799]])

In [ ]:
b = a.to(device) # needs to be stored in a new variable

## Checking the Speed

In [ ]:
import time

size = 10000

# create random matrices on CPU
matrix_cpu1 = torch.randn(size, size) # draws sample from normal distribution
matrix_cpu2 = torch.randn(size, size)

In [ ]:
print(matrix_cpu1[1])

tensor([-1.0371, -0.2264, -0.2381,  ...,  0.9675, -2.5705, -0.6494])


In [ ]:
# Measuring time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time
print("CPU time: ", cpu_time)

CPU time:  13.799824714660645


In [ ]:
# moving to GPU
matrix_gpu1 = matrix_cpu1.to("cuda")
matrix_gpu2 = matrix_cpu2.to("cuda")

# measuring time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize() # ensures all GPU are complete
gpu_time = time.time() - start_time
print("GPU time: ", gpu_time)

GPU time:  0.532477617263794


In [ ]:
# comparing results
print("Speedup (CPU time/GPU time): ", cpu_time/gpu_time)

Speedup (CPU time/GPU time):  25.916253129235464


## Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.7658, 0.6196, 0.2267, 0.5187],
         [0.4316, 0.3842, 0.2858, 0.9388],
         [0.2886, 0.8685, 0.8029, 0.3974]],

        [[0.4187, 0.2356, 0.0021, 0.0251],
         [0.8753, 0.4652, 0.9827, 0.7942],
         [0.5499, 0.7271, 0.7431, 0.2046]]])

In [ ]:
# permute
b.permute(2,0,1).shape # sequence change

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze
c = torch.rand(226,226,3) # typical image size
c.unsqueeze(0).shape # new dimension added at 0th position

# note: We need to unsqueeze to make the image in batches, it's needed as DL models need inputs in batches

torch.Size([1, 226, 226, 3])

In [ ]:
d = torch.rand(1,20)
d.squeeze(0).shape # 0th position removed

torch.Size([20])

## NumPy and PyTorch

In [33]:
import numpy as np
import torch

In [34]:
a = torch.tensor([4,5,6])
a

tensor([4, 5, 6])

In [36]:
b = a.numpy() # changed to numpy array now
b

array([4, 5, 6])

In [37]:
c = np.array([1,2,3])

In [39]:
d = torch.from_numpy(c)
d

tensor([1, 2, 3])