> [!NOTE]  
> Once you train the model, it is desirable that the model should be persist for future use so that we do not need to retrain it again and again. It can be done with the help of dump and load features of joblib package.

In [ ]:
# from sklearn.externals import joblib #ERR ImportError: cannot import name 'joblib' from 'sklearn.externals'

#INFO in new version it's directly
import joblib # It helps you save and load your models 

> I'll go back to yesterday's file to dump and load the model here!

In [4]:
model = joblib.load("iris_model.joblib")

In [5]:
model.predict([[2.7, 2.3, 3.3, 2.8]])

array([1])

### Preprocessing the Data
As we are dealing with lots of data and that data is in raw form, before inputting that data to machine learning algorithms, we need to convert it into meaningful data. This process is called **preprocessing the data**

#### Binarisation

In [6]:
import numpy as np
from sklearn import preprocessing

In [ ]:
Input_data = np.array(
    [
        [2.1, -1.9, 5.5],
        [-1.5, 2.4, 3.5],
        [0.5, -7.9, 5.6],
        [5.9, 2.3, -5.8],
    ]
)

data_binarized = preprocessing.Binarizer(threshold=0.5).transform(Input_data)
data_binarized # NOTE threshold value = 0.5 and that is why, all the values above 0.5 would be converted to 1, and all the values below 0.5 would be converted to 0.

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

#### Mean Removal
This technique is used to eliminate the mean from feature vector so that every feature centered on zero.

In [8]:
print("mean: ", Input_data.mean(axis=0))
print("standard deviation: ", Input_data.std(axis=0))

data_scaled = preprocessing.scale(Input_data)
# Centers each feature around 0 (mean becomes 0), Normalizes standard deviation to 1

print("mean removed: ", data_scaled.mean(axis=0))
print("std dev. removed: ", data_scaled.std(axis=0))


mean:  [ 1.75  -1.275  2.2  ]
standard deviation:  [2.71431391 4.20022321 4.69414529]
mean removed:  [1.11022302e-16 0.00000000e+00 0.00000000e+00]
std dev. removed:  [1. 1. 1.]


#### Scaling  
We use this preprocessing technique for scaling the feature vectors.

In [12]:
minmax_data_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
minmax_data_scaled = minmax_data_scaler.fit_transform(Input_data)
# X_scaled = (X - X_min) / (X_max - X_min)
print("Input Data: \n",Input_data)
print("\nMinMax scaled data:\n", minmax_data_scaled)

Input Data: 
 [[ 2.1 -1.9  5.5]
 [-1.5  2.4  3.5]
 [ 0.5 -7.9  5.6]
 [ 5.9  2.3 -5.8]]

MinMax scaled data:
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]
