In [8]:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

from scipy.sparse.csgraph import bellman_ford

from scipy.sparse.csgraph import depth_first_order, breadth_first_order

# csgraph = compressed sparse graph

### Floyd_Warshall
shortest path between all pairs of elements

In [3]:
arr = np.array([[0, 1, 2], [1, 0, 0], [2, 0, 0]])
newarr = csr_matrix(arr)

print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


### Bellman Ford
shortest path btwn all pairs, handles -ve weights as well

In [7]:
array = csr_matrix(np.array([
    [0,-1,2],
    [1,0,0],
    [2,0,0]
]))

print(bellman_ford(newarr, return_predecessors=True))
# print(bellman_ford(newarr, return_predecessors=True, indices=0)) #INFO calculates from only that node

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


### Depth First Order and Breadth First Order

returns a depth first and breadth first traversal from a node

In [11]:
arr1 = csr_matrix(
    np.array(
        [
            [0, 1, 0, 1],
            [1, 1, 1, 1],
            [2, 1, 1, 0],
            [0, 1, 0, 1],
        ]
    )
)

print(depth_first_order(arr1, 1))
# depth_first_order(csgraph, i_start, directed=True, return_predecessors=True)
# o/p = [1, 0, 3, 2], nodes

print(breadth_first_order(arr1, 1))

(array([1, 0, 3, 2], dtype=int32), array([    1, -9999,     1,     0], dtype=int32))
(array([1, 0, 2, 3], dtype=int32), array([    1, -9999,     1,     1], dtype=int32))
